/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wm_analysissoftware;

import wm_components.*;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Meenakshi
 */
public class wmanalysissoftwareGUI extends javax.swing.JFrame {

    private Component frame;
    private int trial;
    private int genBgd;
    private int drugType;

    /**
     * Creates new form wmanalysissoftwareGUI
     */
    public wmanalysissoftwareGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTrial = new javax.swing.ButtonGroup();
        buttonGroupGenBgd = new javax.swing.ButtonGroup();
        buttonGroupDrugType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonTrialNone = new javax.swing.JRadioButton();
        jRadioButtonTrialPD3 = new javax.swing.JRadioButton();
        jRadioButtonTrialPD5 = new javax.swing.JRadioButton();
        jRadioButtonTrialPD7 = new javax.swing.JRadioButton();
        jRadioButtonGenBgdWT = new javax.swing.JRadioButton();
        jRadioButtonGenBgdTG = new javax.swing.JRadioButton();
        jRadioButtonDrugTypeVeh = new javax.swing.JRadioButton();
        jRadioButtonDrugTypeTest = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldXCoordPt = new javax.swing.JTextField();
        jTextFieldYCoordPt = new javax.swing.JTextField();
        jTextFieldSizePt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Water Maze analysis software");

        jLabel1.setText("Select files");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mouse info:");

        jLabel3.setText("Trial");

        jLabel4.setText("Genetic Background");

        jLabel5.setText("Drug type");

        buttonGroupTrial.add(jRadioButtonTrialNone);
        jRadioButtonTrialNone.setText("None");

        buttonGroupTrial.add(jRadioButtonTrialPD3);
        jRadioButtonTrialPD3.setText("Probe day 3");

        buttonGroupTrial.add(jRadioButtonTrialPD5);
        jRadioButtonTrialPD5.setText("Probe day 5");

        buttonGroupTrial.add(jRadioButtonTrialPD7);
        jRadioButtonTrialPD7.setText("Probe day 7");

        buttonGroupGenBgd.add(jRadioButtonGenBgdWT);
        jRadioButtonGenBgdWT.setText("Wild type");

        buttonGroupGenBgd.add(jRadioButtonGenBgdTG);
        jRadioButtonGenBgdTG.setText("Transgenic");

        buttonGroupDrugType.add(jRadioButtonDrugTypeVeh);
        jRadioButtonDrugTypeVeh.setText("Vehicle");

        buttonGroupDrugType.add(jRadioButtonDrugTypeTest);
        jRadioButtonDrugTypeTest.setText("Test");

        jLabel6.setText("Calculate measures?");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Platform details:");

        jTextFieldXCoordPt.setText("175");

        jTextFieldYCoordPt.setText("175");

        jLabel9.setText("X Coord:");

        jLabel10.setText("Y Coord:");

        jLabel11.setText("Size (in px):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonTrialPD7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonTrialPD3)
                            .addComponent(jRadioButtonTrialNone)
                            .addComponent(jRadioButtonTrialPD5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonGenBgdWT)
                            .addComponent(jRadioButtonGenBgdTG)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldYCoordPt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSizePt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonDrugTypeVeh)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButtonDrugTypeTest)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldXCoordPt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldXCoordPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldYCoordPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSizePt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonTrialNone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTrialPD3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonGenBgdWT)
                            .addComponent(jRadioButtonDrugTypeVeh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonGenBgdTG)
                            .addComponent(jRadioButtonDrugTypeTest))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrialPD5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrialPD7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

//Set platform details/info:
        Platform platform = new Platform();
        platform.setX(Integer.parseInt(jTextFieldXCoordPt.getText()));
        platform.setY(Integer.parseInt(jTextFieldYCoordPt.getText()));

        //Set mouse details/info:
        //Set probe trial info
        String selectedTrial = "";
        if (this.jRadioButtonTrialPD3.isSelected()) {
            trial = Trial.PD3;
            selectedTrial = this.jRadioButtonTrialPD3.getText();
        } else if (this.jRadioButtonTrialPD5.isSelected()) {
            trial = Trial.PD5;
            selectedTrial = this.jRadioButtonTrialPD5.getText();
        } else if (this.jRadioButtonTrialPD7.isSelected()) {
            trial = Trial.PD7;
            selectedTrial = this.jRadioButtonTrialPD7.getText();
        } else {
            trial = Trial.UNDEFINED;
        }

        //Set Genetic Bgd of mice
        String selectedGenBgd = "";
        if (this.jRadioButtonGenBgdTG.isSelected()) {
            genBgd = GeneticBackground.TG;
            selectedGenBgd = this.jRadioButtonGenBgdTG.getText();
        } else {
            genBgd = GeneticBackground.WT;
        }

        //Set Drug type of mice
        String selectedDrugType = "";
        if (this.jRadioButtonDrugTypeTest.isSelected()) {
            drugType = DrugType.TEST;
            selectedDrugType = this.jRadioButtonDrugTypeTest.getText();
        } else {
            drugType = DrugType.VEHICLE;
        }

        // commented out : code to choose multiple files
        JFileChooser Fc = new JFileChooser();
        Fc.setMultiSelectionEnabled(true);
        int result = Fc.showOpenDialog(this);

        File[] dataFiles = null;
        FileReader fReader = null;                      //Reader class : Java class for reading text files (ASCII) 

        if (result == JFileChooser.APPROVE_OPTION) {
            dataFiles = Fc.getSelectedFiles();
            int noFiles = dataFiles.length;                     //stores the number of files selected by the user
            /**
             * Initialization of variables
             */
            String dataString = "";
            int c = 0;
            float xData;
            float yData;
            ArrayList<Mouse> Mice = new ArrayList();

            for (File curFile : dataFiles) {
                int count = 0;
                if (curFile.exists()) {
                    ArrayList<Float> XPos = new ArrayList();
                    ArrayList<Float> YPos = new ArrayList();

                    try {
                        fReader = new FileReader(curFile);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(wmanalysissoftwareGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {

                        while ((c = fReader.read()) != -1) {
                            switch (c) {
                                case '\t':
                                    xData = Float.parseFloat(dataString);
                                    XPos.add(xData);
                                    dataString = "";
                                    break;
                                case '\n':
                                    yData = Float.parseFloat(dataString);
                                    YPos.add(yData);
                                    dataString = "";
                                    break;
                                default:
                                    dataString += (char) c;
                            }
                        }
                        count = count + 1;
                        Mouse M = new Mouse(count, trial, genBgd, drugType, XPos, YPos);
                        Mice.add(M);
                    } catch (IOException ex) {
                        Logger.getLogger(wmanalysissoftwareGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
            
            /*
            Measures newM = new Measures(Mice.get(0), platform);
            System.out.printf("X -> %s \n", Mice.get(0).XData());
            System.out.printf("Y -> %s \n",Mice.get(0).YData());
            
            System.out.printf("PtCorrX -> %s \n", newM.getXPosition());
            System.out.printf("PtCorrY -> %s \n", newM.getYPosition());
            
            System.out.printf("R-Dist -> %s \n", newM.getDistance());
            System.out.printf("R-Vel -> %s \n", newM.getVelocity());
            
            System.out.printf("R-VelAlongPt -> %s \n", newM.getVelocityAlongPt());
            System.out.printf("R-VelPerpendPt -> %s \n", newM.getVelocityPerpendicularPt());
            System.out.printf("R-VelErr -> %s \n", newM.getVelocityError());
             */
            
            //Print out message
            JOptionPane.showMessageDialog(frame, "Files selected. Please select measures to be calculated.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wmanalysissoftwareGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wmanalysissoftwareGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wmanalysissoftwareGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wmanalysissoftwareGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wmanalysissoftwareGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDrugType;
    private javax.swing.ButtonGroup buttonGroupGenBgd;
    private javax.swing.ButtonGroup buttonGroupTrial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDrugTypeTest;
    private javax.swing.JRadioButton jRadioButtonDrugTypeVeh;
    private javax.swing.JRadioButton jRadioButtonGenBgdTG;
    private javax.swing.JRadioButton jRadioButtonGenBgdWT;
    private javax.swing.JRadioButton jRadioButtonTrialNone;
    private javax.swing.JRadioButton jRadioButtonTrialPD3;
    private javax.swing.JRadioButton jRadioButtonTrialPD5;
    private javax.swing.JRadioButton jRadioButtonTrialPD7;
    private javax.swing.JTextField jTextFieldSizePt;
    private javax.swing.JTextField jTextFieldXCoordPt;
    private javax.swing.JTextField jTextFieldYCoordPt;
    // End of variables declaration//GEN-END:variables
}
